### ISSUE TITLE
Having a non-image file in folder breaks widget

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/widget-image-folder#12]
This is in the test version.

Steps to reproduce:
- configure image folder widget in presentation
- add a non-image file(s) to the folder (I only tested with a couple of text files in the folder)
- schedule the presentation or preview it (the problem happens in both)

Result:
Image rotation stops on last item and log fills up with errors like:
Resource interpreted as Image but transferred with MIME type text/plain: "https://www.googleapis.com/download/storage/v1/b/risemedialibrary-e514fd51-…f/o/Image%20Folder%2Fform_letter.txt?generation=1427212074515000&alt=media".
Resource interpreted as Image but transferred with MIME type text/plain: "https://www.googleapis.com/download/storage/v1/b/risemedialibrary-e514fd51-…f/o/Image%20Folder%2Fform_letter.txt?generation=1427212074515000&alt=media".
- only images are shown

How it should work:
Slideshow should loop and not hang while generating a ton of errors
- only images are shown

Link to Presentation:
http://1-08-001.rvauser2.appspot.com/#/PRESENTATION_MANAGE/id=ddb81b66-b2e1-4068-8b7f-2459406452da?cid=e514fd51-fadd-4e19-94af-f92549772c7f

Link to folder reference in widget:
https://www.googleapis.com/storage/v1/b/risemedialibrary-e514fd51-fadd-4e19-94af-f92549772c7f/o?prefix=Image%20Folder%2F   (this contains 7 images and 2 text files)

OS:
Xubuntu 14.04 (preview) and Chrome App Player on Ubuntu 14.04

Chrome Ver:
41.0.2272.101 (laptop version) 40.0.2214.115 (player version)

**Comment by donnapep** [comment]
@mfisher11 I'm getting an RPC error on that Manage Presentation URL, and rva-test.appspot.com is not working for me either. Are you able to get in?

**Comment by donnapep** [comment]
@mfisher11 And just to confirm, this only happens on Ubuntu and not ChromeOS or Windows, correct?

**Comment by donnapep** [comment]
@mfisher11 OK, I was able to view that Presentation by logging into a different account. It doesn't look like you're using the correct test version of the Widget. We bumped it to version 0.1.1 on [this card](http://goo.gl/pZlRGL), and that Presentation is still using 0.1.0. Thx.

**Comment by mfisher11** [comment]
@donnapep Okay.  I'll update the widget URLs and make sure everything looks good.  Thanks.

**Comment by mfisher11** [comment]
@donnapep Closing issue.  Works correctly when widget is updated to point to the correct code base.
