### ISSUE TITLE
Sort order doesn't work as expected.

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/widget-image-folder#14]
More detailed description:  Sorting by name only seems to work when the cache does not contain the the files.  Changing the order once it has been running gives inconsistent results.  Clearing the cache and switching back to the presentation containing the widget fixes it (for name sorting).  Sorting by date doesn't seem to work regardless of cached content.

Steps to reproduce:
1. Assign presentation with image folder widget sorted by name.
2. Let it run.  (if this is the first time for the content, order should be correct)
3. Change the sort order to reverse name, publish.

Result:
Even after the display has updated, order of images are not reverse-name.
* even if you exit the display app, then start it again, order will not be reverse-name.

How it should work:
Images should appear in reverse-name (ascending?) order.

Link to Presentation:
http://rva-test.appspot.com/#/PRESENTATION_MANAGE/id=d1139a47-3cea-4432-a78c-d966781ebd64?cid=b428b4e8-c8b9-41d5-8a10-b4193c789443

OS:
Ubuntu 14.04

Chrome Ver:
Stable (42.0.2311)

Widget version:
0.1.1  (testing)

**Comment by doncy** [comment]
I really need image folder widget to sort by name. Any idea when this will be fixed?

**Comment by doncy** [comment]
I don't know if this will help, but I have one folder that constantly plays in the correct order and one that doesn't. (I tried to make sure that the presentations were created in exactly the same manner and that the settings were exactly the same.) I also tried uploading the files one by one in the order that I wanted that I want them played (to see if the files are being played sorted by modified date.) The modified date does not appear to influence the outcome.  I pasted images of the contents of the two folders in below.

![problem_folder](https://cloud.githubusercontent.com/assets/13004325/8316137/ff80d6ea-19c2-11e5-811a-eac16634dfd3.jpg)

![folder_works](https://cloud.githubusercontent.com/assets/13004325/8316139/0279a840-19c3-11e5-9f2a-6a22704c29a4.jpg)

**Comment by alanclayton** [comment]
@doncy Thanks! Could you provide me with the Preview link to the Presentation you are seeing this issue?

**Comment by doncy** [comment]
I created a test presentation. The presentation includes two items – both
are Image Folder Widgets. One Image Folder Widget uses a folder in Rise
Vision Storage named TestRiseVision. The other Image Folder Widget uses a
folder in Rise Vision Storage named FileTwo. (Sorry, I could have named
these better).



The files in each folder are images that include “File One” and page
numbers and “File Two” and page numbers. The page numbers correlate to the
alphabetical order of the file names. In other words, if the presentation
shows the files in alphabetical order by name, the page numbers will show
as 1-2-3-4.



I include the preview, but note that the preview displays correctly. Here’s
the preview:



http://preview.risevision.com/Viewer.html?type=schedule&id=7cd38ce4-1832-4a22-b40f-838ec9915417



I submitted a more lengthy explanation of the problem, a description of my
displays, and more detail about the test and its results at:



https://community.risevision.com/rise_vision_inc/topics/new-release-the-image-folder-widget?utm_source=notification&utm_medium=email&utm_campaign=new_comment&utm_content=reply_button&reply[id]=15830239#reply_15830239

As you can tell, I’m very motivated to help find a solution. Don’t hesitate
to suggest ways that I can help.



Don Yost

Maple City Health Care Center

(W) 574-534-3300 ext. 205

(C) 574-202-6032

dyost@mchcc.com



*From:* Alan Clayton [mailto:notifications@github.com]
*Sent:* Wednesday, June 24, 2015 9:02 AM
*To:* Rise-Vision/widget-image-folder
*Cc:* doncy
*Subject:* Re: [widget-image-folder] Sort order doesn't work as expected.
(#14)



@doncy <https://github.com/doncy> Thanks! Could you provide me with the
Preview link to the Presentation you are seeing this issue?

—
Reply to this email directly or view it on GitHub
<https://github.com/Rise-Vision/widget-image-folder/issues/14#issuecomment-114861048>
.

**Comment by AlexKolenoff** [comment]
I have confirmed that alphabetical sort order may work the first time a presentation plays, but then shows images out of order once the presentation is refreshed or restarted.

It appears to play in correct order in Preview.

Preview Link: http://preview.risevision.com/Viewer.html?type=presentation&id=11f9dd50-3101-4431-9b27-f40be210fec0

OS: Windows 7
Player: RisePlayerPackagedApp 1.24.36
Chrome v. 43.0.2357.130

**Comment by doncy** [comment]
Can you let me know about the progress being made on this issue?
I need the image folder widget to work.  Thanks.

**Comment by donnapep** [comment]
@doncy Thanks for your inquiry. We are currently working on a fix for this issue and hope to release it soon.

**Comment by donnapep** [comment]
Order setting was removed and images are sorted alphabetically by default.

**Comment by donnapep** [comment]
@doncy If you restart your players, you should see the files sort in alphabetical order.

**Comment by doncy** [comment]
I’ll run a test either later today or tomorrow.



I’ll only communicate with you if I see problems.



This is great news. Thanks very much for your work.



Don Yost

Maple City Health Care Center

(W) 574-534-3300 ext. 205

(C) 574-202-6032

dyost@mchcc.com



*From:* Donna Peplinskie [mailto:notifications@github.com]
*Sent:* Thursday, July 23, 2015 1:30 PM
*To:* Rise-Vision/widget-image-folder
*Cc:* doncy
*Subject:* Re: [widget-image-folder] Sort order doesn't work as expected.
(#14)



@doncy <https://github.com/doncy> If you restart your players, you should
see the files sort in alphabetical order.

—
Reply to this email directly or view it on GitHub
<https://github.com/Rise-Vision/widget-image-folder/issues/14#issuecomment-124175230>
.
