### ISSUE TITLE
Widget does not play through images when in schedule.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-image-folder#15]
Steps to reproduce:
1. Create a presentation with one or more Image Folder Widget Placeholders.
2. Create a new schedule
3. Add the presentation that you created in step 1 to the new schedule. 
4. Add any other presentation to the schedule. Move the presentation with the Image Folder Widget to the second position in the schedule. 

Result:
The presentation created in step 1 does not scroll through the Images contained in the Image Folder Widget(s).

How it should work:
Image Folder Widget should scroll through all images whether it is contained in a scheduled with other presentations or not.

Link to Schedule:
http://preview.risevision.com/Viewer.html?type=schedule&id=46808268-7cc5-4fc2-8de4-b1486da051ec

OS:
OS X 10.10

Chrome Ver:
43

**Comment by btfrise** [comment]
FYI @alanclayton this issue was brought up in the community. Can we get this scheduled for a review?

**Comment by alanclayton** [comment]
@btfrise I'm unable to replicate this. Here is the schedule I setup per your instructions, http://rva.risevision.com/#/SCHEDULE_MANAGE/id=44e8e9c5-9fa2-4549-b233-fe0a6b994dab?cid=3c86db8b-5ab5-4ee1-85a5-284317371990

Can you review and let me know what is different between what I've setup vs what you have. Thanks

**Comment by btfrise** [comment]
@alanclayton Have you run this on a display?

**Comment by btfrise** [comment]
@alanclayton I am confident that this is a scheduling issue. When presentations are scheduled to play 300 seconds or more, the Image Folder Widget does not scroll through images. So far I have been able to test 60, 90, 120 seconds with no issue. I will continue testing, but I do not believe this is an issue with the Widget itself, more likely scheduling.

**Comment by alanclayton** [comment]
@btfrise what was the conclusion here?

**Comment by btfrise** [comment]
@alanclayton this ended up being an issue with the presentation and was resolved. I'm closing this.
