### ISSUE TITLE
Files deleted from storage still remain in presentation

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/widget-image-folder#17]
Steps to reproduce:
1. Assign a presentation containing the image folder widget and referencing a folder with images.
2. Delete one (or more) of the files.

Result:
Presentation still shows deleted image (even after two hours)

How it should work:
Deleted image should not appear in presentation (within 15 minutes)

Link to Presentation:
http://rvauser.appspot.com/#/PRESENTATION_MANAGE/id=6a62f2c4-0122-41de-b207-af4e1d8fbb29?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55

OS:
Linux, Windows, OS X, Chrome OS

Chrome Ver:
43.0.2357.125 (technically stable, beta, and dev)

**Comment by donnapep** [comment]
@mfisher11 This is a duplicate of https://github.com/Rise-Vision/storage-server/issues/197

**Comment by mfisher11** [comment]
Closing issue.
