### ISSUE TITLE
Multiple Image Folder Widgets in one Placeholder - presentation freezing/stopped playing

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/widget-image-folder#28]
**To Duplicate**
1. Create a presentation with four Image Folder widgets in one Placeholder (see http://rva.risevision.com/#/PRESENTATION_MANAGE/id=384ff046-f6f5-4d73-8aef-ba8b6c92f122?cid=960b72df-9af7-476b-8a47-b67ded4c779d)
2. Run in schedule (see http://rva.risevision.com/#/SCHEDULE_MANAGE/id=549db014-0f3a-46e4-87e5-486a317cf2e7?cid=960b72df-9af7-476b-8a47-b67ded4c779d)

When you run the presentation on the Display the image freezes (ie observed that it freezes within five minutes)

**Expected result**
Presentation to not freeze.

**Other notes**
Have seen other users with a similar set up (ie more than one Image Folder in a Placeholder) and no reported freezing so we may need to look at other scenarios.  ie http://rva.risevision.com/#/PRESENTATION_MANAGE/id=47229833-eab1-41be-98ba-681432ee3f22?cid=960b72df-9af7-476b-8a47-b67ded4c779d - they are on Windows.  So this may be Linux OS.
Originally I thought it was memory issues, so have asked user to optimize, but even after optimizing the images I see freezing occur on my own VM.

First reported https://community.risevision.com/rise_vision_inc/topics/will-swapping-cenique-for-raspberry-improve-reliability-and-solve-hang-ups?topic-reply-list%5Bsettings%5D%5Bfilter_by%5D=all&topic-reply-list%5Bsettings%5D%5Breply_id%5D=16340760#reply_16340760

**Environment**
Test: Linux 32-bit, RisePlayer 2015.10.12.15.11, Chrome 46.0.2490.86
User: Linux 32-bit, RisePlayer 2015.10.12.15.11, Chrome 46.0.2490.86

**Comment by lapinnoir** [comment]
https://app.intercom.io/a/apps/d85f4ah4/inbox/all/conversations/1517910507

**Comment by rodrigopavezi** [comment]
@lapinnoir I have implemented a fix so I was wondering if you could check that it works with your presentation. 

It is deployed to:
http://s3.amazonaws.com/widget-image-folder-test/0.1.1/dist/widget.html
https://s3.amazonaws.com/widget-image-folder-test/0.1.1/dist/settings.html

http://rva.risevision.com/#/GADGET_MANAGE/id=9037e9df-3843-4eca-8f09-60ed8fc570bb?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013

cheers

**Comment by lapinnoir** [comment]
:+1: tested on that presentation @rodrigopavezi

**Comment by rodrigopavezi** [comment]
@lapinnoir the fix has been deployed to prod https://github.com/Rise-Vision/widget-image-folder/pull/29. I  reckon this issue can be closed. cheers
