### ISSUE TITLE
When in schedule with other presentations, Widget causing crashing.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-image-folder#30]
How to replicate
1. Create a presentation that contains the Image Folder Widget
2. Create a presentation containing any other content
3. Place both presentations in the schedule

Expected results
Presentations should play through without crashing player

Actual results
Presentations play through, and begin crashing player after a short period of time.

Windows 7 32bit, Chrome 47 (stable), Chrome 48 (beta)
Rise Windows Player

Demo schedule: http://rva.risevision.com/#/SCHEDULE_MANAGE?cid=e113f8d6-de1c-4c26-b160-4ef1c4589957

**Comment by btfrise** [comment]
FYI @alanclayton this is what is crashing our uptime. With Image Folder Widget removed, the schedule does not crash.

**Comment by alanclayton** [comment]
@btfrise A update was just pushed a little bit ago that fixed an issue with multiple instance of image folder in a single playlist. Can you confirm if you cleared cache and tested with the latest version? 

@rodrigopavezi @donnapep @stulees FYI

**Comment by btfrise** [comment]
@alanclayton I've confirmed this is still an issue after the fix that wa pushed.

**Comment by robb-price** [comment]
@btfrise @alanclayton I have been running this this afternoon on a VM and physical Win 7 32 Bit machine, and so far no issues. I recreated a brand new Schedule from the steps above and all works as expected.

Myself or someone in CS will be testing with Chrome 48 next week to see if this or the RSS with Images issue we discussed still exists.

**Comment by lapinnoir** [comment]
@robb-price i have 48 on win 7 32bit

**Comment by robb-price** [comment]
@lapinnoir Awesome! Can you add that Display in the Uptime Company, and assign it to this Schedule: https://apps.risevision.com/schedules/details/4ceb9f12-6250-46d8-906f-7bdc4195cd0a?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55.

We need to watch to see if the Player on the Display crashes while running that Presentation. 

Thanks!

**Comment by robb-price** [comment]
@lapinnoir How did Chrome 48 on Win7 32 bit fare with that presentation? Any issues?

**Comment by lapinnoir** [comment]
@robb-price No issue, VM setting is base memory 1024MB, video memory 27MB, 1 CPU (or standard setting).

**Comment by robb-price** [comment]
Could not replicate, closing.
