### ISSUE TITLE
Storage files containing special characters do not display.

### ISSUE THREAD

**Issue by ashleighalmeida** [Rise-Vision/widget-image-folder#31]
<b>How it works now:</b>
User has an image folder containing images with parentheses () within the file name.
When the user runs their presentation, image folder will appear blank.

<b>How it should work:</b>
File names containing special characters should display.

I removed the parentheses from the file names and the Image Folder ran as it should.

I tested this out with other widgets, and it appears this issue is only relevant to Image Folders.
I also rotated between other special characters using brackets and ?!, ran into the same issue with the folder.

https://trello.com/c/CjvQOfOD/1179-bug-which-widgets-do-not-pull-storage-files-with-special-characters

http://rva.risevision.com/#/PRESENTATION_MANAGE/id=dd227ced-7bc4-4514-aea5-80ed42a2eecc?cid=f114ad26-949d-44b4-87e9-8528afc76ce4

**Comment by ashleighalmeida** [comment]
https://app.intercom.io/a/apps/d85f4ah4/inbox/apa@risevision.com/conversations/1664807218

**Comment by donnapep** [comment]
Was able to reproduce the issue of a file with parentheses in the file name not showing, but ? and ! are working just fine.
