### ISSUE TITLE
Alignment is lost every other iteration of the playlist in Windows Chrome App.

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/widget-image-folder#6]
This is the presentation used (in the Uptime company):

http://rva.risevision.com/#PRESENTATION_MANAGE/id=4caa09cf-f802-4b0f-b50f-ecbe22ebf076/company=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55

Expected behavior:
Alignment stays the same throughout multiple loops of the image slideshow.

Actual behavior:
On windows (only), all channels of chrome (stable, beta, dev) it looks like the pattern is--
first iteration of slideshow the alignment is as configured in the presentation.
second iteration of slideshow, all images align to the top left.
third is back to normal.
fourth is top left.
etc.

This behavior does not occur on Linux, Mac, or ChromeOS.

**Comment by donnapep** [comment]
Fixed by https://github.com/Rise-Vision/widget-image-folder/pull/7

**Comment by mfisher11** [comment]
@donnapep Confirmed fixed.  Thanks.
